<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Lyric.Core\Lyric.Core.csproj" />
      <ProjectReference Include="..\Lyric.AST\Lyric.AST.csproj" />
      <ProjectReference Include="..\Lyric.Resolver\Lyric.Resolver.csproj" />
    </ItemGroup>

</Project>
